Update limits.
octarinesec/octarine-operator pull request #47
Opened 2021-07-23 18:20 UTC by sergeykostov

2021-07-27 12:11 UTC, yurado commented on controllers/cbcontainersruntime_controller.go
> +	if err := setDefaultResourceRequirements(&cbContainersRuntime.Spec.SensorSpec.Resources, "64Mi", "30m", "1024Mi", "200m"); err != nil {
Let's give a higher limit for CPU usage as well. I was thinking something like `500m`

2021-07-27 13:18 UTC, sergeykostov commented
Done.

2021-08-02 09:42 UTC, yurado approved these changes

2021-08-02 11:53 UTC, BenRub requested changes
@sergeykostov Hi Sergey, please update the kubebuilder defaults in the comments on the api type as well.
This will be relevant when we'll use CRD v1

2021-08-03 08:29 UTC, yurado approved these changes

2021-08-05 06:06 UTC, closed without merging

2021-08-05 06:06 UTC, sergeykostov commented
Local branch