Refactor runtime resolver service to a headless service
octarinesec/octarine-operator pull request #84
Opened 2022-04-07 10:30 UTC by davidf146

2022-04-18 10:44 UTC, sergeykostov approved these changes

2022-04-20 10:35 UTC, yurado requested changes

2022-04-20 10:35 UTC, yurado commented on cbcontainers/state/components/resolver_service.go
> +	setAsHeadlessService, err := utils.IsVersionGreaterThan(agentSpec.Version, "2.4.0")
Please extract `2.4.0` to a constant

2022-04-20 10:57 UTC, davidf146 commented on cbcontainers/state/components/resolver_service.go
> +	setAsHeadlessService, err := utils.IsVersionGreaterThan(agentSpec.Version, "2.4.0")
Fixed.

2022-04-20 11:18 UTC, yurado approved these changes

2022-04-25 13:08 UTC, merged